include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - public_member_api_docs
    - type_annotate_public_apis
    - prefer_const_constructors
    - prefer_final_fields
    - avoid_print
    - prefer_single_quotes
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_dynamic_calls
    - unnecessary_new
    - void_checks
formatter:
  trailing_commas: preserve